language: java
install:
    - mkdir composer-java-api
    - cd composer-java-api
    - git clone https://github.com/pulse00/Composer-Java-Bindings.git .
    - git checkout develop
    - mvn clean install -DskipTests
script: mvn clean install
